export const login = 'login';

export const logout = 'logout';

export const errorLogin = 'errorLogin';

export const FETCH_FACTORIES_BEGIN   = 'FETCH_Factories_BEGIN';
export const FETCH_FACTORIES_SUCCESS = 'FETCH_Factories_SUCCESS';
export const FETCH_FACTORIES_FAILURE = 'FETCH_Factories_FAILURE';


export const FETCH_FACTORIES_DETAILS_BEGIN   = 'FETCH_FACTORIES_DETAILS_BEGIN';
export const FETCH_FACTORIES_DETAILS_SUCCESS = 'FETCH_FACTORIES_DETAILS_SUCCESS';
export const FETCH_FACTORIES_DETAILS_FAILURE = 'FETCH_FACTORIES_DETAILS_FAILURE';

export const FETCH_MARKETS_BEGIN   = 'FETCH_MARKETS_BEGIN';
export const FETCH_MARKETS_SUCCESS = 'FETCH_MARKETS_SUCCESS';
export const FETCH_MARKETS_FAILURE = 'FETCH_MARKETS_FAILURE';

export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
